### ISSUE TITLE
OCP quickstart output `resource_group_names` does not contain proper values

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-landing-zone#851]
- Deploy OCP quickstart with prefix: `con-qs`
- The `resource_group_names` output contains the group names with the prefix:
![image](https://github.com/user-attachments/assets/cd951a0e-b761-47c8-91d5-3507978e4373)

These should have the actual name of the groups, including the prefix. For example: `con-qs-management-rg`

**Comment by jor2** [comment]
@ocofaigh seems this was intentional, any reasoning why?

https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/14b3656b0787f7da81163a98726b739a90b20ca1/resource_groups.tf#L42

https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/blob/14b3656b0787f7da81163a98726b739a90b20ca1/outputs.tf#L274

**Comment by ocofaigh** [comment]
@jor2 no idea - we may have inherited this

**Comment by toddgiguere** [comment]
If I had to guess, the stripping of prefix for that other local variable probably has to do with all the mapping that happened at the pattern level, which would NOT include the prefix. So the local.resrouce_groups probably wanted to preserve the original names used in mappings.
